# Generated by Django 3.1.7 on 2021-03-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
