# Generated by Django 3.1.7 on 2021-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20210309_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
